config/routes.rb
Rails.application.routes.draw do

  resources :textsublimes
  root 'textsublimes#index'

end

app/models/textsublime.rb
class Textsublime < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/textsublimes_controller.rb
class TextsublimesController < ApplicationController
	before_action :find_textsublime, only: [:show, :edit, :update, :destroy]


	def index
		
	end


	def show
		
	end

	def new
		@textsublime = Textsublime.new
	end

	def create
		@textsublime = Textsublime.new textsublimes_params

		if @textsublime.save
			redirect_to @textsublime
		else
			render 'new'
		end
		
	end

	def edit
		
	end

	def update
		if @textsublime.update textsublimes_params
			redirect_to @textsublime
		else
			render 'edit'
		end

	end

	def destroy
		@textsublime.destroy
		redirect_to textsublimes_path
		
	end


	private

def textsublimes_params
	params.require(:textsublime).permit(:title, :description, :link)
end


def find_textsublime
	@textsublime = Textsublime.find(params[:id])
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/textsublimes_helper.rb
module TextsublimesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SublimeText</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/textsublimes/_form.html.erb
<%= form_for @textsublime do |f| %>
	<% if @textsublime.errors.any? %>
		<h2><%= pluralize(@textsublime.errors.count, "error") %> prevented this text  from saving:</h2>
		<ul>
			<% @textsublime.errors.full_text.each do |txt| %>
				<li><%= txt %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title, "Combination" %><br>
	<%= f.text_field :title %>

	<br>
	<br>

	<%= f.label :description, "Write function" %><br>
	<%= f.text_area :description %>

	<br>
	<br>

	<%= f.submit "Save", class: "btn btn-default"%>

<% end %>

app/views/textsublimes/edit.html.erb
<h1> Edit sublime text </h1>

<%= render 'form' %>

app/views/textsublimes/index.html.erb
<h1>hallo world!!</h1>

app/views/textsublimes/new.html.erb
<h1> New sublime text </h1>

<%= render 'form' %>

app/views/textsublimes/show.html.erb
<%= @textsublime.title %><br>
<%= @textsublime.description %>

<br>
<br>

<%= link_to "Edit", edit_textsublime_path(@textsublime) %>
<%= link_to "Delete", textsublime_path(@textsublime), method: :delete, data: { confirm: "Are you want delete?"} %>